title: "Abhijeet Bhowmick"
description: "Analytics Platforms, Cost Control & BI Governance<br>Helping teams modernize analytics without runaway cloud costs or broken trust"
google_analytics:
theme: jekyll-theme-cayman